### ISSUE TITLE
Thảo luận về đề tài

### ISSUE THREAD

**Issue by KienTrann** [XQuyTran/APP-CQ18#1]
Chào các bạn nhóm 3,

Mình thấy ban đầu tụi em định làm về đề tài "Phát sinh số ngẫu nhiên ...", sau đó thì đổi sang "Xác định loại bệnh thực vật bằng CNN". Đề tài này hơi trùng với đề tài của nhóm 8, nhóm 8 cũng là làm về CNN nhưng là để phân loại ảnh chữ số viết tay.

Mình muốn các đề tài khác nhau, chứ trùng thì không được hay lắm. Tụi em xem thử có thể chuyển sang mô hình máy học khác không (vẫn là xác định loại bệnh thực vật); ví dụ, mình thấy Random Forest hoặc XGBoost là 2 mô hình rất đáng để tìm hiểu. 

(Vụ này mình cũng đã có trao đổi với nhóm 8, nhưng có vẻ nhóm 8 không tự tin để đổi sang mô hình khác lắm; nếu xét về thời điểm đăng ký đề tài thì nhóm 8 đăng ký trước nhóm em.)

**Comment by XQuyTran** [comment]
Dạ em chào Thầy ạ,

Sau khi nhận yêu cầu từ Thầy, nhóm đã họp và quyết định thay đổi đề tài sang sử dụng mô hình XGBoost. Nhóm cũng đã cập nhật đăng ký đề tài.

**Comment by KienTrann** [comment]
Uh, cảm ơn nhóm em.
